# Generated by Django 5.2 on 2025-07-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerprofile_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
